export { dayElement } from "./elements/dayElement.js";
export { dayFormatElement } from "./elements/dayFormatElement.js";
export { guessElement } from "./elements/guessElement.js";
export { monthElement } from "./elements/monthElement.js";
export { monthFormatElement } from "./elements/monthFormatElement.js";
export { newDateButtonElement } from "./elements/newDateButtonElement.js";
export { yearElement } from "./elements/yearElement.js";
export const dateElement = document.querySelector("[data-date]");
export const resultElement = document.querySelector("[data-result]");
export const settingsElement = document.querySelector("[data-settings]");
export const timerElement = document.querySelector("[data-timer]");